# The services of the project.
#
# Each service listed will be deployed to power your project.

mysql:
    type: mysql:10.6
    disk: 5120

redis:
    type: redis:7.0

opensearch:
    type: opensearch:2
    disk: 1024
