# The services of the project.
#
# Each service listed will be deployed to power your project.

mariadb:
    type: mariadb:11.4
    disk: 5120

#redis:
#    type: redis:7.2

cache:
    type: valkey:8.0

opensearch:
    type: opensearch:3
    disk: 1024

#files:
#    type: network-storage:2.0
#    disk: 5120
